### ISSUE TITLE
Meeting times change

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#11]
Hey all - I've been looking through the doodle poll to figure out when meeting times work for everybody. Now that we have sub-group projects, I wonder how you all feel about this:

We meet as an entire group every two weeks. This would be _Thursdays at 3:30pm_. This should be an hour-long meeting where we give updates to each project, go over admin stuff, and discuss challenges we're facing / ideas we've got / etc.

We meet in sub-groups every two weeks (on alternate weeks from full group meetings). These would also be an hour long, but focused on more nitty gritty details of the project. Times would be:
_Wednesdays at 3:00pm_ for @kaiweitan @juanshishido 
_Thursdays at 3:30pm_ for @dariusmehri and @nlin3330 

I will try to make it to all of these meetings, and hopefully @anthonysuen or @danielturek can make it to group meetings as well.

What do you guys think about this? Good idea? My concern about always meeting as a full group is that all of our schedules don't overlap, and we may not be able to cover questions in a particular sub-group to the extent that we'd like.

Let me know what you all think.

**Comment by dariusmehri** [comment]
i'm good, d.

On Tue, Mar 17, 2015 at 1:53 PM, Chris Holdgraf notifications@github.com
wrote:

> Hey all - I've been looking through the doodle poll to figure out when
> meeting times work for everybody. Now that we have sub-group projects, I
> wonder how you all feel about this:
> 
> We meet as an entire group every two weeks. This would be _Thursdays at
> 3:30pm_. This should be an hour-long meeting where we give updates to
> each project, go over admin stuff, and discuss challenges we're facing /
> ideas we've got / etc.
> 
> We meet in sub-groups every two weeks (on alternate weeks from full group
> meetings). These would also be an hour long, but focused on more nitty
> gritty details of the project. Times would be:
> _Wednesdays at 3:00pm_ for @kaiweitan https://github.com/kaiweitan
> @juanshishido https://github.com/juanshishido
> _Thursdays at 3:30pm_ for @dariusmehri https://github.com/dariusmehri
> and @nlin3330 https://github.com/nlin3330
> 
> I will try to make it to all of these meetings, and hopefully @anthonysuen
> https://github.com/anthonysuen or @danielturek
> https://github.com/danielturek can make it to group meetings as well.
> 
> What do you guys think about this? Good idea? My concern about always
> meeting as a full group is that all of our schedules don't overlap, and we
> may not be able to cover questions in a particular sub-group to the extent
> that we'd like.
> 
> Let me know what you all think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/11.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by testchange** [comment]
good suggestion! I am fine with it.

**Comment by anthonysuen** [comment]
That sounds like a great idea. Are we meeting this Thursday at 3:30?

Anthony

On Tue, Mar 17, 2015 at 1:53 PM, Chris Holdgraf notifications@github.com
wrote:

> Hey all - I've been looking through the doodle poll to figure out when
> meeting times work for everybody. Now that we have sub-group projects, I
> wonder how you all feel about this:
> 
> We meet as an entire group every two weeks. This would be _Thursdays at
> 3:30pm_. This should be an hour-long meeting where we give updates to
> each project, go over admin stuff, and discuss challenges we're facing /
> ideas we've got / etc.
> 
> We meet in sub-groups every two weeks (on alternate weeks from full group
> meetings). These would also be an hour long, but focused on more nitty
> gritty details of the project. Times would be:
> _Wednesdays at 3:00pm_ for @kaiweitan https://github.com/kaiweitan
> @juanshishido https://github.com/juanshishido
> _Thursdays at 3:30pm_ for @dariusmehri https://github.com/dariusmehri
> and @nlin3330 https://github.com/nlin3330
> 
> I will try to make it to all of these meetings, and hopefully @anthonysuen
> https://github.com/anthonysuen or @danielturek
> https://github.com/danielturek can make it to group meetings as well.
> 
> What do you guys think about this? Good idea? My concern about always
> meeting as a full group is that all of our schedules don't overlap, and we
> may not be able to cover questions in a particular sub-group to the extent
> that we'd like.
> 
> Let me know what you all think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/11.

## 

Anthony Suen

**Comment by juanshishido** [comment]
This is good for me, too. @kaiweitan shall we meet at BIDS again?

Thanks, Chris.

**Comment by choldgraf** [comment]
OK, let's all plan to meet in our separate groups this week. @dariusmehri you are still out of town, correct? If so, then @nlin3330 which would you prefer, today or tomorrow?

Next week, we'll meet as a group to prepare some materials for our mid-semester presentation the Monday after.

@kaiweitan and @juanshishido are you able to meet today at 3:00pm in BIDS?

**Comment by nlin3330** [comment]
Tomorrow works better for me

**Comment by choldgraf** [comment]
Sounds good. I'll plan on meeting with @nlin3330 tomorrow to talk about
progress on the network stuff. Juan, Kai, and I will meet today unless I
hear otherwise from them.

**Comment by testchange** [comment]
Hey juan and chris, i am hosting a senior today. So i cannot come for today session. sorry for the late notice!

**Comment by choldgraf** [comment]
Hi Kai - in that case, can you please give your updates and commit your
latest code to github by this afternoon? I am creating an issue for this
week's meetings.

Chris

**Comment by choldgraf** [comment]
See #12 for this week. I'm closing this issue because it sounds like we have a plan for meeting times.
