### ISSUE TITLE
Images for Monday's presentation (no meetups this week)

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#13]
Hey guys, I hope you're all having a good break. I'll get to specific questions / issues with projects in a little while, but for now two quick things:
1. No meetings this week. Instead, we'll communicate via github / slack
2. We need some pretty pictures by this Monday for the short BIDS presentation I'm giving. This should be a good opportunity to get some input from people at BIDS and make connections.
3. I spoke with Aman and we're shooting for a brainstorm session in a few weeks...I'll keep you posted.

Post any questions / thoughts to this issue and we can discuss from there @kaiweitan @juanshishido @dariusmehri @nlin3330 @anthonysuen

**Comment by dariusmehri** [comment]
hey chris, did you get the ones i just sent?

On Thu, Mar 26, 2015 at 2:56 PM, Chris Holdgraf notifications@github.com
wrote:

> Hey guys, I hope you're all having a good break. I'll get to specific
> questions / issues with projects in a little while, but for now two quick
> things:
> 1. No meetings this week. Instead, we'll communicate via github / slack
> 2. We need some pretty pictures by this Monday for the short BIDS
>    presentation I'm giving. This should be a good opportunity to get some
>    input from people at BIDS and make connections.
> 3. I spoke with Aman and we're shooting for a brainstorm session in a
>    few weeks...I'll keep you posted.
> 
> Post any questions / thoughts to this issue and we can discuss from there
> @kaiweitan https://github.com/kaiweitan @juanshishido
> https://github.com/juanshishido @dariusmehri
> https://github.com/dariusmehri @nlin3330 https://github.com/nlin3330
> @anthonysuen https://github.com/anthonysuen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/13.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
Hey Darius, how did you send them? Email, or did you post to github?

**Comment by dariusmehri** [comment]
email to berkeley-dsc/purchasing

doesn't this automatically post it?

i sent them all in a zip file

darius

On Thu, Mar 26, 2015 at 2:58 PM, Chris Holdgraf notifications@github.com
wrote:

> Hey Darius, how did you send them? Email, or did you post to github?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86732501
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
Ah - no, github issues only deals with images, but not other file types. A
better strategy would be to put it into dropbox or the google drive and
include a link.

**Comment by dariusmehri** [comment]
hey chris, i just emailed them to your gmail, darius

On Thu, Mar 26, 2015 at 3:13 PM, Chris Holdgraf notifications@github.com
wrote:

> Ah - no, github issues only deals with images, but not other file types. A
> better strategy would be to put it into dropbox or the google drive and
> include a link.
> 
> On Thu, Mar 26, 2015 at 3:11 PM, dariusmehri notifications@github.com
> wrote:
> 
> > email to berkeley-dsc/purchasing
> > 
> > doesn't this automatically post it?
> > 
> > i sent them all in a zip file
> > 
> > darius
> > 
> > On Thu, Mar 26, 2015 at 2:58 PM, Chris Holdgraf <
> > notifications@github.com>
> > wrote:
> > 
> > > Hey Darius, how did you send them? Email, or did you post to github?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86732501
> > 
> > > .
> > 
> > ## 
> > 
> > Darius Mehri
> > Ph.D. Candidate, Sociology
> > University of California, Berkeley
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86736033
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86736372
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
Sounds good. You have access to the group's Google Drive, right?

**Comment by dariusmehri** [comment]
yeah, do you want me to put it up there as well, darius

On Thu, Mar 26, 2015 at 4:02 PM, Chris Holdgraf notifications@github.com
wrote:

> Sounds good. You have access to the group's Google Drive, right?
> 
> On Mar 26, 2015 3:29 PM, "dariusmehri" notifications@github.com wrote:
> 
> > hey chris, i just emailed them to your gmail, darius
> > 
> > On Thu, Mar 26, 2015 at 3:13 PM, Chris Holdgraf <
> > notifications@github.com>
> > wrote:
> > 
> > > Ah - no, github issues only deals with images, but not other file
> > > types.
> > > A
> > > better strategy would be to put it into dropbox or the google drive and
> > > include a link.
> > > 
> > > On Thu, Mar 26, 2015 at 3:11 PM, dariusmehri <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > email to berkeley-dsc/purchasing
> > > > 
> > > > doesn't this automatically post it?
> > > > 
> > > > i sent them all in a zip file
> > > > 
> > > > darius
> > > > 
> > > > On Thu, Mar 26, 2015 at 2:58 PM, Chris Holdgraf <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > Hey Darius, how did you send them? Email, or did you post to
> > > > > github?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86732501
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Darius Mehri
> > > > Ph.D. Candidate, Sociology
> > > > University of California, Berkeley
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86736033
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86736372
> > 
> > > .
> > 
> > ## 
> > 
> > Darius Mehri
> > Ph.D. Candidate, Sociology
> > University of California, Berkeley
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86740360
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-86748740
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
No worries, I'll put it up there for now, we should put results in the
data/results folder

**Comment by choldgraf** [comment]
Hey Darius - I just took a look at the graphs. They look interesting!

Can you give a stab at coming up with a "story" to tell judging from this
data? Something along the lines of "by looking at the network across
quarters of a year, we can see that _____, which is interesting because
_____". This will be an important part of all our projects as we start to
get some results in.

**Comment by choldgraf** [comment]
Hey all - I hope you guys had a great break. A reminder that I'm chatting (very) briefly about this project at BIDS tea today. If you've got any new pretty pictures, feel free to send them to me.

Let's meet all as a group this week to have a checkpoint session for where we're at. Everybody can talk about what they've accomplished so far, and get some feedback.

Let me know if you've got any questions etc.

**Comment by dariusmehri** [comment]
sure, thursday at 3:30?

On Mon, Mar 30, 2015 at 9:47 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey all - I hope you guys had a great break. A reminder that I'm chatting
> (very) briefly about this project at BIDS tea today. If you've got any new
> pretty pictures, feel free to send them to me.
> 
> Let's meet all as a group this week to have a checkpoint session for where
> we're at. Everybody can talk about what they've accomplished so far, and
> get some feedback.
> 
> Let me know if you've got any questions etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/13#issuecomment-87746494
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
Yup, Thursday at 3:30pm, whole group

**Comment by testchange** [comment]
ok noted! I may drop by later.
