### ISSUE TITLE
Meeting - Thursday, April 2nd at 3:30pm

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#14]
Hey guys, thanks again for sending me your work so far. In my (admittedly biased) opinion, this project was the most impressive of the ones that presented, you guys are great :)

We'll have a brief meeting tomorrow at 3:30pm. @anthonysuen, maybe you can meet to discuss the best course of action for the final stretch of this project?

Here's what I've got. Let me know if there's anything you'd like to discuss:
- Recap of what we've worked on so far. I'll go through the powerpoint presentation slides and you guys can give an update to the group of where we're at.
- Planning out the final month of this project. (we've got until the beginning of May so want to make sure there are some deliverables before then)
- Planning an analysis finalization session with Andrew + Aman from a data consulting group

@dariusmehri @anthonysuen @nlin3330 @dariusmehri @kaiweitan

**Comment by dariusmehri** [comment]
sounds good, we will have a new strategy for the network analysis based on
my conversation with andrew clark

once we get up to speed with all that is required with network x we should
be able to crank out some nice visualizations

darius

On Wed, Apr 1, 2015 at 10:41 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey guys, thanks again for sending me your work so far. In my (admittedly
> biased) opinion, this project was the most impressive of the ones that
> presented, you guys are great :)
> 
> We'll have a brief meeting tomorrow at 3:30pm. @anthonysuen
> https://github.com/anthonysuen, maybe you can meet to discuss the best
> course of action for the final stretch of this project?
> 
> Here's what I've got. Let me know if there's anything you'd like to
> discuss:
> - Recap of what we've worked on so far. I'll go through the powerpoint
>   presentation slides and you guys can give an update to the group of where
>   we're at.
> - Planning out the final month of this project. (we've got until the
>   beginning of May so want to make sure there are some deliverables before
>   then)
> - Planning an analysis finalization session with Andrew + Aman from a
>   data consulting group
> 
> @dariusmehri https://github.com/dariusmehri @anthonysuen
> https://github.com/anthonysuen @nlin3330 https://github.com/nlin3330
> @dariusmehri https://github.com/dariusmehri @kaiweitan
> https://github.com/kaiweitan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/14.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by juanshishido** [comment]
I will try to call in.

In thinking about what we can provide, I had this idea (it may have been discussed before). If we can predict when the various departments in the UC system will need items, we can have them order it ahead of time. This way, _if_ there are instances of higher shipping costs due to expedited shipping, we can prevent that.

**Comment by agcinsf** [comment]
If there is a call in number I will dial in. 

Ac

**Comment by dariusmehri** [comment]
hey guys, i won't able to make it to the meeting, have an interview i need
to prepare for, if there is a number,  i can dial in using skype,
otherwise, i will be meeting with nick tomorrow and i can give an update on
the next steps via email, darius

On Wed, Apr 1, 2015 at 10:41 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey guys, thanks again for sending me your work so far. In my (admittedly
> biased) opinion, this project was the most impressive of the ones that
> presented, you guys are great :)
> 
> We'll have a brief meeting tomorrow at 3:30pm. @anthonysuen
> https://github.com/anthonysuen, maybe you can meet to discuss the best
> course of action for the final stretch of this project?
> 
> Here's what I've got. Let me know if there's anything you'd like to
> discuss:
> - Recap of what we've worked on so far. I'll go through the powerpoint
>   presentation slides and you guys can give an update to the group of where
>   we're at.
> - Planning out the final month of this project. (we've got until the
>   beginning of May so want to make sure there are some deliverables before
>   then)
> - Planning an analysis finalization session with Andrew + Aman from a
>   data consulting group
> 
> @dariusmehri https://github.com/dariusmehri @anthonysuen
> https://github.com/anthonysuen @nlin3330 https://github.com/nlin3330
> @dariusmehri https://github.com/dariusmehri @kaiweitan
> https://github.com/kaiweitan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/14.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by anthonysuen** [comment]
Hey guys,

I will be in class until 4pm but would love to catch up on developments.

Anthony

On Wed, Apr 1, 2015 at 10:41 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey guys, thanks again for sending me your work so far. In my (admittedly
> biased) opinion, this project was the most impressive of the ones that
> presented, you guys are great :)
> 
> We'll have a brief meeting tomorrow at 3:30pm. @anthonysuen
> https://github.com/anthonysuen, maybe you can meet to discuss the best
> course of action for the final stretch of this project?
> 
> Here's what I've got. Let me know if there's anything you'd like to
> discuss:
> - Recap of what we've worked on so far. I'll go through the powerpoint
>   presentation slides and you guys can give an update to the group of where
>   we're at.
> - Planning out the final month of this project. (we've got until the
>   beginning of May so want to make sure there are some deliverables before
>   then)
> - Planning an analysis finalization session with Andrew + Aman from a
>   data consulting group
> 
> @dariusmehri https://github.com/dariusmehri @anthonysuen
> https://github.com/anthonysuen @nlin3330 https://github.com/nlin3330
> @dariusmehri https://github.com/dariusmehri @kaiweitan
> https://github.com/kaiweitan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/14.

## 

Anthony Suen

**Comment by choldgraf** [comment]
Hmm - it sounds like a few people won't be able to make it today. My vote is to **postpone this meeting until next week**. 

This may work out for the better because I spoke with Aman Ahuja from the Data Guild yesterday. He said he'd be happy to sit in on a meeting that we have in order to figure out how to best-finish these projects[1]. 

I can send out a when2meet to make sure that his and Andrew's schedules work with the time, and we can have a proper brainstorm to finish out the semester.

@dariusmehri and @nlin3330, I'll send a message to get an update after your meeting tomorrow.
@juanshishido and @kaiweitan, I'd like to know where you're at with respect to the text classification and time-to-completion analyses.

So recap: **No meeting today**, and we'll reschedule for next week. Instead, you guys can update me electronically and I'll give the group an update via github.

How do you guys feel about this?

## 

[1] @agcinsf, Aman also mentioned that he's interested in doing a more structured "ideation" phase for new projects once these are done. I think it makes sense to save this for later, because we've only got a month to finish up these projects and I want to make sure that they get completed. What do you think?

**Comment by dariusmehri** [comment]
this works best for me, i will send an update tomorrow after meeting with
nick, darius

On Thu, Apr 2, 2015 at 12:07 PM, Chris Holdgraf notifications@github.com
wrote:

> Hmm - it sounds like a few people won't be able to make it today. My vote
> is to _postpone this meeting until next week_.
> 
> This may work out for the better because I spoke with Aman Ahuja from the
> Data Guild yesterday. He said he'd be happy to sit in on a meeting that we
> have in order to figure out how to best-finish these projects[1].
> 
> I can send out a when2meet to make sure that his and Andrew's schedules
> work with the time, and we can have a proper brainstorm to finish out the
> semester.
> 
> @dariusmehri https://github.com/dariusmehri and @nlin3330
> https://github.com/nlin3330, I'll send a message to get an update after
> your meeting tomorrow.
> @juanshishido https://github.com/juanshishido and @kaiweitan
> https://github.com/kaiweitan, I'd like to know where you're at with
> respect to the text classification and time-to-completion analyses.
> 
> So recap: _No meeting today_, and we'll reschedule for next week.
> Instead, you guys can update me electronically and I'll give the group an
> update via github.
> 
> How do you guys feel about this?
> 
> [1] @agcinsf https://github.com/agcinsf, Aman also mentioned that he's
> interested in doing a more structured "ideation" phase for new projects
> once these are done. I think it makes sense to save this for later, because
> we've only got a month to finish up these projects and I want to make sure
> that they get completed. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/14#issuecomment-89012855
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by juanshishido** [comment]
Sounds good, @choldgraf. Thanks!

**Comment by agcinsf** [comment]
I am definitely open to an ideation phase when these projects are done.  Let me know when/where and I will be there with my colleagues.
