### ISSUE TITLE
Meetings and/or updates this week

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#16]
Hey folks - In lieu of meetings this week, I'd like an update of where we are with respect to the current projects. For any of these, if you guys wanna meet to chat about things then I am happy to do so.

@nlin3330 and @dariusmehri - I see that you've pushed some commits to the repository recently. Is the code/notebooks in a format that would be worth taking a look at?

@juanshishido - Did you see the notes from the last brainstorm meeting? Should be some suggestions / goals for wrapping up in there. Let me know what progress you're making.

@kaiweitan - Was it clear what we were discussing at the meeting last Friday regarding blanket POs? Let me know if you'd like to talk about analyses / coding stuff to finish this.

Only a couple weeks left everybody, let's finish strong.

**Comment by dariusmehri** [comment]
we could but nick and i don't have new results to show yet, perhaps at the
end of this week,  is the final date may 5 during the bids fair?

darius

On Wed, Apr 15, 2015 at 10:28 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey folks - In lieu of meetings this week, I'd like an update of where we
> are with respect to the current projects.
> 
> @nlin3330 https://github.com/nlin3330 and @dariusmehri
> https://github.com/dariusmehri - I see that you've pushed some commits
> to the repository recently. Is the code/notebooks in a format that would be
> worth taking a look at?
> 
> @juanshishido https://github.com/juanshishido - Did you see the notes
> from the last brainstorm meeting? Should be some suggestions / goals for
> wrapping up in there. Let me know what progress you're making.
> 
> @kaiweitan https://github.com/kaiweitan - Was it clear what we were
> discussing at the meeting last Friday regarding blanket POs? Let me know if
> you'd like to talk about analyses / coding stuff to finish this.
> 
> Only a couple weeks left everybody, let's finish strong.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/16.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
OK sounds good, keep me updated. Yes, final date for analyses will be first
week of May. We can put together some figures / explanations for the fair,
and then focus on documentation from then on out.

**Comment by nlin3330** [comment]
Basically I'm trying to create a function that automatically subsets the data by periods of time 
(total time/some number) and does a bunch of calculations/creates a graph. However, the data doesn't look consistent as some periods of time have no data so that is one bug that I still need to fix.

**Comment by testchange** [comment]
@choldgraf 

yea we are meeting at 4pm to discuss about the agenda for TTC. I have already looked through a couple of efficiency metrics.

**Comment by choldgraf** [comment]
Perfect - let me know how the meeting goes

**Comment by testchange** [comment]
Sorry for the confusion. I meant to have a meeting with you 4pm at BIDS. Are you available during that time?

**Comment by choldgraf** [comment]
oh I thought you meant you and @juanshishido...I can meet at 4pm at BIDS

**Comment by choldgraf** [comment]
@juanshishido are you available then?

**Comment by choldgraf** [comment]
hey @agcinsf, just had a meeting with @kaiweitan to come up with ways to suss out Blanket POs. Do you have information about the size of various departments on campus? We had a hard time finding public information about that but maybe there's internal information sources along those lines?

**Comment by juanshishido** [comment]
Hey @choldgraf and @kaiweitan. Thought the meeting was scheduled for tomorrow. I was not on campus today.

**Comment by dariusmehri** [comment]
are we having a meeting tomorrow?

d.

On Wed, Apr 15, 2015 at 7:37 PM, Juan Shishido notifications@github.com
wrote:

> Hey @choldgraf https://github.com/choldgraf and @kaiweitan
> https://github.com/kaiweitan. Thought the meeting was scheduled for
> tomorrow. I was not on campus today.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/16#issuecomment-93621604
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by juanshishido** [comment]
That's what's on my calendar. BIDS - Group meeting 3:30-4:30.

**Comment by agcinsf** [comment]
It should all be on CalAnswers, the campus BI dashboard tool. I will try and pull out the data tomorrow.

Ac

**Comment by dariusmehri** [comment]
ok, please send a number so i can call in, darius

On Wed, Apr 15, 2015 at 7:44 PM, Juan Shishido notifications@github.com
wrote:

> That's what's on my calendar. BIDS - Group meeting 3:30-4:30.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/16#issuecomment-93622408
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
Ah - I think that we got thrown off a bit because of the re-scheduled group meeting last week. My vote is to keep it with sub-groups as-needed, rather than meeting as a full group. @juanshishido, if you'd like to chat about the project I'm happy to meet tomorrow. @dariusmehri and @nlin3330, you are welcome to join if you like but we can have a group meeting next week.

**Comment by dariusmehri** [comment]
group meeting next week, we should have results then, darius

On Wed, Apr 15, 2015 at 10:06 PM, Chris Holdgraf notifications@github.com
wrote:

> Ah - I think that we got thrown off a bit because of the re-scheduled
> group meeting last week. My vote is to keep it with sub-groups as-needed,
> rather than meeting as a full group. @juanshishido
> https://github.com/juanshishido, if you'd like to chat about the
> project I'm happy to meet tomorrow. @dariusmehri
> https://github.com/dariusmehri and @nlin3330
> https://github.com/nlin3330, you are welcome to join if you like but we
> can have a group meeting next week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/16#issuecomment-93642537
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
sounds good - see you next week then. @juanshishido, let me know what you'd like to do

**Comment by juanshishido** [comment]
It'd be good to touch base, @choldgraf. Maybe just a 30-minute meeting. See you tomorrow. Thanks!

**Comment by choldgraf** [comment]
Sounds great, see you there.

**Comment by choldgraf** [comment]
Hey all - I'm looking through some of the latest commits now. Sounds like we are making some progress on function-ifying the code that we've created so far. Once we've created functions, we should put them into python modules rather than keep them in the ipython notebooks. The notebooks should just be for prototyping things, and then for demonstrating code / scripting.

To put a function in a module, you just need to create a file that ends in `.py`. Then, put it in a folder with a file called `__init__.py`. Finally, add that folder's parent to your `$PYTHONPATH`, or within a python session, you can run:

``` python
import sys
sys.path.append('path/to/folder/parent')
```

Now, you can define functions in that file and import them.

For example, for me, I need to add `~/gdrive/github/personal/bids_purchasing/` to my path. Within the `bids_purchasing` folder is the "script" folder that we care about. After I do this, I can do `from script import network` and it will import everything inside `network.py` as a module.

I've added an `__init__.py` file to our script folder, as well as empty `.py` files for network stuff and time clustering stuff (what I'm working on). Let's start to add functions there, and import from them in the notebooks.
