### ISSUE TITLE
Group meeting Thursday, April 23rd at 3:30pm

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#17]
Hey guys - last week we met individually, so tomorrow we've got a group meeting tomorrow to go over progress on everybody's project.

Primary agenda is:
- discuss what's left to be done on each project
- cover any questions that you guys have come across in the last few days.
- come up with a final format for deliverables

It looks like the final presentation for this project will be **May 6th at 6:00pm at BIDS**. I'll make an issue for this when I confirm that date.

**Comment by choldgraf** [comment]
Whoops - forgot to include @berkeley-dsc/purchasing (see above for more info)

**Comment by dariusmehri** [comment]
sure, will be there, darius

On Wed, Apr 22, 2015 at 10:55 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey guys - last week we met individually, so tomorrow we've got a group
> meeting tomorrow to go over progress on everybody's project.
> 
> Primary agenda is:
> - discuss what's left to be done on each project
> - cover any questions that you guys have come across in the last few
>   days.
> - come up with a final format for deliverables
> 
> It looks like the final presentation for this project will be _May 6th at
> 6:00pm at BIDS_. I'll make an issue for this when I confirm that date.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/17.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by testchange** [comment]
so there's no sub-group meeting today?

**Comment by choldgraf** [comment]
No, just a group meeting tomorrow.

**Comment by choldgraf** [comment]
Hey guys - just a reminder about meeting today at 3:30pm. I don't think that updates and discussion will take the full time, so I'll plan on sticking around to work on BIDS projects until about 4:30pm or so regardless. If you guys like, stick around and we can work together to bounce ideas/questions off of each other as they come up.

See you guys soon!

**Comment by choldgraf** [comment]
Hey guys - there in 5

**Comment by choldgraf** [comment]
# Network Stuff
- Nick's having an error with "month" subsetting
- NetworkX visualization options aren't great
- Having trouble plotting labels of nodes
- Look into feature generation for gephy

# Blanket PO stuff
- Find Andrew's data about blanket POs
- Get CalAnswer data access
- Come up with a new feature to use on top of number of line items per PO

# Text classification
- Structured Topic Modeling in r might be better @dariusmehri will send info about STM in r
- How to choose the right number of topics to use @dariusmehri will e-mail papers on this
- Figure out how to interpret the topics

**Comment by choldgraf** [comment]
@dariusmehri and @nlin3330 have you guys checked out GraphViz [1] and its python libraries [2]? It's a pretty nice graph plotting library. Might be useful, and I think you can use it with NetworkX

[1] http://www.graphviz.org/
[2] https://pypi.python.org/pypi/graphviz

**Comment by choldgraf** [comment]
Hey @agcinsf, do you have access to CalAnswers? We thought we could look up department information (e.g., size) with this, but it looks like neither me nor @kaiweitan have access. If you know of another place we could look for this information let me know.

**Comment by agcinsf** [comment]
I though CalAnswers was open to anyone with a CalNet ID.  You just have to register and then use one of the correct browsers, because the tool is restrictive. 

If you don't have access, check with Alex Butler.  He might be able to pull the data you need. 

Alex, can you help Chris and the gang?

Thanks!

Ac

**Comment by choldgraf** [comment]
Ahh I see - I think I've figured out how to request access (we'll see if they give it to me).

@kaiweitan you should request access too, then I think you can get the data

**Comment by davclark** [comment]
Did y'all find this? https://api-central.berkeley.edu/

On Mon, Apr 27, 2015 at 1:53 PM, Chris Holdgraf notifications@github.com
wrote:

> Closed #17 https://github.com/berkeley-dsc/purchasing/issues/17.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/17#event-291329497.

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by choldgraf** [comment]
That looks interesting - worth checking out, @kaiweitan and @agcinsf?
