### ISSUE TITLE
Final presentations Wednesday, May 6th at 6:00pm at BIDS

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#18]
Hey @berkeley-dsc/purchasing - this is a thread to coordinate information / images / etc for the BIDS final presentation. Here's the info:

**Where** - BIDS
**When** - May 6th, 6:00pm
**What** - Probably a 10-15 minute presentation with a bit more info than last time

Let me know if you guys can be there...this'll be the last official presentation for this project, so you should come and get some credit. There will **also be a happy hour afterward**.

I'm going to need some updated pretty pictures, and a few talking points for each project. We can discuss tomorrow.

It would be great if @agcinsf could be there as well...let me know if that's possible so I can tell Anthony etc.

Thanks for all your hard work guys, getting close to the finish line!

**Comment by dariusmehri** [comment]
why so late in the day???

this makes it difficult for folks with kids

darius

On Wed, Apr 22, 2015 at 11:04 AM, Chris Holdgraf notifications@github.com
wrote:

> Hey @berkeley-dsc/purchasing
> https://github.com/orgs/berkeley-dsc/teams/purchasing - this is a
> thread to coordinate information / images / etc for the BIDS final
> presentation. Here's the info:
> 
> _Where_ - BIDS
> _When_ - May 6th, 6:00pm
> _What_ - Probably a 10-15 minute presentation with a bit more info than
> last time
> 
> Let me know if you guys can be there...this'll be the last official
> presentation for this project, so you should come and get some credit.
> There will _also be a happy hour afterward_.
> 
> I'm going to need some updated pretty pictures, and a few talking points
> for each project. We can discuss tomorrow.
> 
> It would be great if @agcinsf https://github.com/agcinsf could be there
> as well...let me know if that's possible so I can tell Anthony etc.
> 
> Thanks for all your hard work guys, getting close to the finish line!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/18.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
I think they Anthony thought that later would increase attendance...I
didn't really have a say in the matter, but I will let the organizing team
know about this issue.

**Comment by danielturek** [comment]
Apologies for the evening event.  I hope all team members are able to attend, to receive the credit you all deserve.  As Chris mentioned, the logic behind the 6pm start time was to allow industry partners with 5pm COB to attend.  Truly, there was no 100% optimal solution here.

**Comment by dariusmehri** [comment]
ok, i just may not be able to attend, i have to check w/ my wife, darius

On Wed, Apr 22, 2015 at 11:12 AM, Chris Holdgraf notifications@github.com
wrote:

> I think they Anthony thought that later would increase attendance...I
> didn't really have a say in the matter, but I will let the organizing team
> know about this issue.
> 
> On Wed, Apr 22, 2015 at 11:08 AM, dariusmehri notifications@github.com
> wrote:
> 
> > why so late in the day???
> > 
> > this makes it difficult for folks with kids
> > 
> > darius
> > 
> > On Wed, Apr 22, 2015 at 11:04 AM, Chris Holdgraf <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > Hey @berkeley-dsc/purchasing
> > > https://github.com/orgs/berkeley-dsc/teams/purchasing - this is a
> > > thread to coordinate information / images / etc for the BIDS final
> > > presentation. Here's the info:
> > > 
> > > _Where_ - BIDS
> > > _When_ - May 6th, 6:00pm
> > > _What_ - Probably a 10-15 minute presentation with a bit more info than
> > > last time
> > > 
> > > Let me know if you guys can be there...this'll be the last official
> > > presentation for this project, so you should come and get some credit.
> > > There will _also be a happy hour afterward_.
> > > 
> > > I'm going to need some updated pretty pictures, and a few talking
> > > points
> > > for each project. We can discuss tomorrow.
> > > 
> > > It would be great if @agcinsf https://github.com/agcinsf could be
> > > there
> > > as well...let me know if that's possible so I can tell Anthony etc.
> > > 
> > > Thanks for all your hard work guys, getting close to the finish line!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/berkeley-dsc/purchasing/issues/18.
> > 
> > ## 
> > 
> > Darius Mehri
> > Ph.D. Candidate, Sociology
> > University of California, Berkeley
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/berkeley-dsc/purchasing/issues/18#issuecomment-95287333
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/18#issuecomment-95288605
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by dariusmehri** [comment]
i see, no worries, darius

On Wed, Apr 22, 2015 at 11:50 AM, Daniel Turek notifications@github.com
wrote:

> Apologies for the evening event. I hope all team members are able to
> attend, to receive the credit you all deserve. As Chris mentioned, the
> logic behind the 6pm start time was to allow industry partners with 5pm COB
> to attend. Truly, there was no 100% optimal solution here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/18#issuecomment-95299767
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
hey @agcinsf, any chance that you can make it to this? The organizers are trying to get a head count on collaborators who are going to be present.

**Comment by agcinsf** [comment]
Absolutely I will be there.  

Ac

**Comment by choldgraf** [comment]
@dariusmehri and @nlin3330, I really like the graphs and networks that you've put on the google drive (in the `network_analysis_data` folder). It sounds like there are a lot of interesting stats in there (e.g., betweenness). Can you create some quick summary plots of these (e.g., the distribution of betweenness scores for all departments for one month over 3 years).

**Comment by dariusmehri** [comment]
hi chris, i am working on this, the graphs are interesting but there is not
much detail because they are not broken down according to item type, i have
item type graphs but haven't posted them yet, i will send out all plots,
graphs, story, conclusion, what to do going forward, and so on, this
evening in power point,  and will post all graphs and so on on drive, i
will be focusing on a few measures and graphs for the presentation (so not
to confuse the participants or muddle up with too much info), darius

On Mon, May 4, 2015 at 4:42 PM, Chris Holdgraf notifications@github.com
wrote:

> @dariusmehri https://github.com/dariusmehri and @nlin3330
> https://github.com/nlin3330, I really like the graphs and networks that
> you've put on the google drive (in the network_analysis_data folder). It
> sounds like there are a lot of interesting stats in there (e.g.,
> betweenness). Can you create some quick summary plots of these (e.g., the
> distribution of betweenness scores for all departments for one month over 3
> years).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/18#issuecomment-98885549
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
ok that sounds great. I'll try to incorporate some of your plots in the
poster as well. The bigger (in resolution) the images are, the better.
