### ISSUE TITLE
Project finalization meeting this week

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#19]
Hey all - let's have a final work session to hash out final plots / graphs that we'll use in the presentation on Tuesday/Wednesday (or at least to make a clear road to create something by the weekend). We can give a brief update (just a few mins) and spend the rest of the time working to finish up what we've got.

Are you guys free for a working meeting around 3:00pm on Wednesday at BIDS? Let me know if this sounds good.

@berkeley-dsc/purchasing

**Comment by dariusmehri** [comment]
i can make it but prefer thursday, darius

On Mon, Apr 27, 2015 at 1:53 PM, Chris Holdgraf notifications@github.com
wrote:

> Hey all - let's have a final work session to hash out final plots / graphs
> that we'll use in the presentation on Tuesday/Wednesday (or at least to
> make a clear road to create something by the weekend). We can give a brief
> update (just a few mins) and spend the rest of the time working to finish
> up what we've got.
> 
> Are you guys free for a working meeting around 3:00pm on Wednesday at
> BIDS? Let me know if this sounds good.
> 
> @berkeley-dsc/purchasing
> https://github.com/orgs/berkeley-dsc/teams/purchasing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/19.

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
I'm gonna be out of town on Thursday through Sunday. Could potentially meet Thu morning but it'd be close...

**Comment by dariusmehri** [comment]
ok, wed is good with me, d.

On Mon, Apr 27, 2015 at 1:57 PM, Chris Holdgraf notifications@github.com
wrote:

> I'm gonna be out of town on Thursday through Sunday. Could potentially
> meet Thu morning but it'd be close...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/19#issuecomment-96817590
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by juanshishido** [comment]
Hey, @choldgraf. My knee is still messed up from a biking mishap last week. Trying not to walk much. Didn't make it to campus yesterday (Tuesday). Not sure I will tomorrow, either. I can video in, though!

**Comment by choldgraf** [comment]
I'm treating this as a "working meeting". I'll be there to work on stuff
I've been doing for this project, and to help out with anybody else's part.
I think it's important that we finalize these materials as a team, rather
than on our own. It will make the end product more useful for Andrew and
teach us more in the process.

If people can't make it today, that's ok so long as we've got something to
show on Monday. I'll send out a few things that I'd like from you guys by
the end of the weekend, and we can go from there. We should have a
finalizing meeting next week or the week after in that case.

Chris

**Comment by dariusmehri** [comment]
i can get a bunch of stuff out by friday, including images and stats, i can
also make a movie, and i'll include a powerpoint with slides to tell a
story, and i will coordinate with nick on latest he as been working on,
it's best for me not to attend meeting today because i kill about an hour
going to campus and back,  darius

On Wed, Apr 29, 2015 at 9:35 AM, Chris Holdgraf notifications@github.com
wrote:

> I'm treating this as a "working meeting". I'll be there to work on stuff
> I've been doing for this project, and to help out with anybody else's part.
> I think it's important that we finalize these materials as a team, rather
> than on our own. It will make the end product more useful for Andrew and
> teach us more in the process.
> 
> If people can't make it today, that's ok so long as we've got something to
> show on Monday. I'll send out a few things that I'd like from you guys by
> the end of the weekend, and we can go from there. We should have a
> finalizing meeting next week or the week after in that case.
> 
> Chris
> 
> On Wed, Apr 29, 2015 at 12:39 AM, Juan Shishido notifications@github.com
> wrote:
> 
> > Hey, @choldgraf https://github.com/choldgraf. My knee is still messed
> > 
> > up from a biking mishap last week. Trying not to walk much. Didn't make
> > it
> > to campus yesterday (Tuesday). Not sure I will tomorrow, either. I can
> > video in, though!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/berkeley-dsc/purchasing/issues/19#issuecomment-97334717
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/19#issuecomment-97493678
> .

## 

Darius Mehri
Ph.D. Candidate, Sociology
University of California, Berkeley

**Comment by choldgraf** [comment]
OK, sounds good. If you aren't going to be on campus anyway then I don't
want you to lose time in transit. I'll send out a couple specifics I'd like
from you guys just to make sure we've got what we need. Either way, I'll be
at BIDS at 3pm to work on this.

**Comment by agcinsf** [comment]
What time is the event tomorrow?  Its at 6pm right?

**Comment by davclark** [comment]
The Data Science Faire is tomorrow (Tuesday) from 1-4:30pm:

http://bids.berkeley.edu/events/bids-spring-2015-data-science-faire

The Data Science Collaborative final project presentations will be Wednesday at 6pm:

http://bids.berkeley.edu/events/data-science-collaborative-final-project-presentations

**Comment by choldgraf** [comment]
To add to that - the Data Faire highlights research from all over UC
Berkeley, and the BIDS collaborative is just a part of that. The "final
presentations" event on Wednesday is BIDS-specific, and is probably the
preferred option if you had to pick.
