### ISSUE TITLE
Figure out who needs to go on the purchasing team

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/purchasing#2]
Get github user IDs, and add them to this team: https://github.com/orgs/berkeley-dsc/teams/purchasing

I've already given that team read/write access to this repo

**Comment by choldgraf** [comment]
I think most people have access now... @juanshishido @nlin3330 @dariusmehri @kaiweitan @anthonysuen @danielturek

**Comment by choldgraf** [comment]
All users should be added to the github repo, so I'm closing this.
