### ISSUE TITLE
Get your team on Slack

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/purchasing#3]
They should be able to sign up using their berkeley.edu address:

https://msdse.slack.com/messages/berkeley-dsc/

**Comment by choldgraf** [comment]
I looked through Slack and there is some discussion from the BIDS team. That said, I don't see a ton of value-added for this project specifically. How do people feel about holding off on using slack for this project and using github issues for discussing things instead?

**Comment by dariusmehri** [comment]
my vote is to stick with github for communication and google drive for data

**Comment by davclark** [comment]
As one of the main instigators of slack - if things are working, then it's
fine to keep them that way. Keep in mind that part of the ideal is to have
discussions be public, so that folks can go back and see what happened in
discussions. So, if there's a lot in the black hole of email, that'd be a
good thing to move to slack.

Also - the goal is eventually to get other members of BIDS chiming in on
your projects - which you could do by posting to the berkeley-dsc group on
Slack - in particular, you might @mention someone.

D

**Comment by anthonysuen** [comment]
I agree that while currently Slack isn't very active, it can be a useful to get feedback when the team hits a major roadblock that requires additional help.

**Comment by dariusmehri** [comment]
i'm definitely not against moving to slack,  at this point though i think our goal should be to get results, instead of adding one more way of communicating that we must get up to speed with, so i think we should leave things as is, for now, if that is ok with you guys

**Comment by choldgraf** [comment]
I am willing to migrate any miscellaneous / quick interactions to Slack, though I'd like project-specific questions to remain with their respective github issues. @davclark or @anthonysuen, do you have opinions about using github issues vs. slack for discussion project questions etc?

**Comment by davclark** [comment]
If it makes sense to be on GitHub, then it should be on GitHub, definitely.

D

On Tue, Mar 17, 2015 at 1:57 PM, Chris Holdgraf notifications@github.com
wrote:

> I am willing to migrate any miscellaneous / quick interactions to Slack,
> though I'd like project-specific questions to remain with their respective
> github issues. @davclark https://github.com/davclark or @anthonysuen
> https://github.com/anthonysuen, do you have opinions about using github
> issues vs. slack for discussion project questions etc?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-dsc/purchasing/issues/3#issuecomment-82597539
> .

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by choldgraf** [comment]
Sounds good - I will note that @juanshishido and I are both on Slack, where we've created a "Purchasing" room to discuss questions about this project. I am not going to make any requirements for people to use Slack, only that if they have any kind of project-related question, they **either** use Slack or they use github, but not email.

However, I still urge you guys to check it out, because I think it may be useful:
https://msdse.slack.com/messages/berkeley-dsc/
