### ISSUE TITLE
Finding product categories

### ISSUE THREAD

**Issue by choldgraf** [berkeley-dsc/purchasing#5]
It looks like this is going to be a fairly difficult thing to with with the current data. Here's what Andrew said:

> Categorization is difficult.  I can get you a “general classification” of the spend, but it will be messy.

He'll send something soon, but it looks like we may need to figure this out ourselves.

**Comment by dariusmehri** [comment]
i was just thinking about this and something hit me that may be useful: the suppliers typically specialize in supplying specific products so maybe we can categorize according to specialty, i.e a supplier that supplies software will unlikely sell chemicals, and so on

**Comment by choldgraf** [comment]
I think that's a good idea. This would work for the more specialized suppliers. Some might be too "general" (e.g., Staples), but I think it's worth trying to see how it comes out.

Maybe we could pick the 100 most common suppliers, and categorize each one?

**Comment by choldgraf** [comment]
Closed because @juanshishido is working on this with #9
